DATA_DIR = "../DATA"
SAVED_DIR ="../STORED_EMBED"
NUM_EXAMPLES = 2
NUM_SENTENCES_PER_CHUNK = 5
MIN_TOKEN_LEN = 30
BATCH_SIZE = 32
DEVICE = "cpu"
MODEL_NAME = "all-mpnet-base-v2"
NUM_NEAREST_SEARCH = 5

